### ISSUE TITLE
test data request

### ISSUE THREAD

**Issue by michalkvasnicka** [a-jd/npsn#2]
Could you add some test data to verify and show basic functionality of your package?

**Comment by a-jd** [comment]
Working on getting some data that is approved for distribution. Will upload in 2-3 months.

**Comment by michalkvasnicka** [comment]
> Will upload in 2-3 months.

So quickly ... ???

**Comment by michalkvasnicka** [comment]
Description of input data in dg.py file is so brief, that is nearly impossible to create it.

So, well ... As I said in my comment deleted by owner: **Without any relevant test data set is this package useless for anybody except the owner.**
